server:
  port: 9000


spring:
  application:
    name: prometheus

# actuator
management:
  server:
    port: 9001 # actuator ????
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
      base-path: /console # ???? /console/prometheus ???????
  endpoint:
    prometheus:
      enabled: true
