server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpa?characterEncoding=utf8&useSSL=false
    username: root
    password: 1111
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true # 显示 sql 语句
    hibernate:
      ddl-auto: create # //自动创建表，并且退出时不删除表
#    open-in-view: false
