server:
  port: 9000

spring:
  application:
    name: rabbitmq
  rabbitmq:
    host: env-base
    port: 15670 # HAProxy 监听器端口
    username: root
    password: 1111
#    listener:
#      simple:
#        acknowledge-mode: auto # 开启重试机制，这里必须是 auto，否则不生效！
#        retry:
#          enabled: true # 开启消费者失败重试
#          initial-interval: 5000ms # 失败等待时常
#          max-attempts: 5 # 最大重试次数(包括第一次消费)
