server:
  port: 9000

spring:
  application:
    name: rabbitmq
  rabbitmq:
    host: env-base
    port: 5672
    username: root
    password: 1111
    publisher-confirm-type: correlated # 开启发送方确认机制
#    listener:
#      simple:
#        acknowledge-mode: manual
